### ISSUE TITLE
Switch order of colours and quarters?

### ISSUE THREAD

**Issue by statshero** [theodi/dashboards#167]
Q1 turquoise
Q2 lightBlue
Q3 midBlue
Q4 darkBlue

![screen shot 2014-04-28 at 10 37 15](https://cloud.githubusercontent.com/assets/1837585/2815361/e08b3402-ceb8-11e3-9dbd-339e902352ac.png)

**Comment by Floppy** [comment]
![bikeshed](http://www.shedscene.com/image/cache/Apex%20Bike%20Shed-500x500.jpg)

**Comment by statshero** [comment]
This shed does not follow ODI style guidelines.
