### ISSUE TITLE
Update currency conversion

### ISSUE THREAD

**Issue by Floppy** [theodi/dashboards#193]
Need to pull in currency conversion from some live feed, not a fixed value as now. @agentGav to specify the right place to get the data from.

**Comment by Floppy** [comment]
OK, we're going to use a static value, but update it on an annual basis and expose what the value IS and when it was worked out in the tooltip.

**Comment by alisonwalters** [comment]
sounds good :)

**Comment by andylolz** [comment]
@Floppy [is this a workable thing](http://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20yahoo.finance.xchange%20where%20pair%20in%20%28%22GBPEUR%22,%20%22GBPUSD%22,%20%22GBPJPY%22,%20%22GBPKRW%22%29&env=store://datatables.org/alltableswithkeys&format=json)? (Sorry if you’ve already had this conversation!)

**Comment by Floppy** [comment]
Mmm, could be. Let me recheck with Gavin, it's been a while and there were financial implications of how we display it.

**Comment by Floppy** [comment]
Actually, reading back, yes, using that data to drive the static factor would be fine.
